steps:
  - label: ':hammer: Tests'
    command: echo 'test'
    
  - wait

  - label: ':package: Package'
    command: echo 'packaging'

  - wait

  - label: ':debian: Publish'
    command: echo 'publishing'

  - block: ':shipit: Release'
    branches: 'master'

  - label: ':github: Release'
    command: 'scripts/build-github-release.sh'
    artifact_paths: 'releases/**/*'
    branches: 'master'

  - wait

  - label: ':whale: Update images'
    command: 'scripts/release-docker.sh'
    branches: 'master'
    agents:
      queue: 'deploy'