steps:
  - label: ':hammer: Tests'
    command: echo 'test'
    
  - wait

  - label: ':package: Package'
    command: echo 'package and push to ec2 registry'

  - block: ":rocket: Deploying"
    prompt: "Choose system to deploy"
    fields: 
      - select: "Type"
        key: "release-type"
        default: "develop"
        options:
        - label: "Dev"
          value: "develop"
        - label: "Staging"
          value: "staging"

  - command: release.sh
    label: ":rocket:"